apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-brod
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-brod@sha256:cedb4e40003ad5543b40569bddfe037ecd3f8f8cf675b48ba2d9a600b34ace76
        name: my-nodejs
        resources: {}
status: {}
